<?php  include $_SERVER["DOCUMENT_ROOT"]."/inc/dbcon.php";

	$ADMIN=$_POST['ADMIN'];
	$SELLER_CODE=$_POST['SELLER_CODE'];
	$PRODUCT_ID=$_POST['PRODUCT_ID'];
	$PRODUCT_NAME=removeHackTag($_POST['PRODUCT_NAME']);
	$PRODUCT_NAME_CH=removeHackTag($_POST['PRODUCT_NAME_CH']);
	$SHORTINFO=removeHackTag(addslashes($_POST['SHORTINFO']));
	$SHORTINFO_CH=removeHackTag(addslashes($_POST['SHORTINFO_CH']));
	$PROMOTION_YN=$_POST['PROMOTION_YN'];
	$PROMOTION_COLOR=$_POST['PROMOTION_COLOR'];
	$PROMOTION_CONTENTS=removeHackTag(addslashes($_POST['PROMOTION_CONTENTS']));
	$cate1=$_REQUEST['cate1'];
	$cate2=$_REQUEST['cate2'];
	$mate=$_REQUEST['mate'];//소재
	$pt=$_REQUEST['pt'];//퍼센트
	$COLOR=$_REQUEST['COLOR'];
	$COLOR_CH=$_REQUEST['COLOR_CH'];
	$WHOLESALE_PRICE=removeHackTag($_POST['WHOLESALE_PRICE']);
	$WHOLESALE_PRICE_CH=removeHackTag($_POST['WHOLESALE_PRICE_CH']);
	$DISP=$_POST['DISP'];
	$DISPLAY_START_DATE=$_POST['DISPLAY_START_DATE'];
	$DISPLAY_END_DATE=substr($_POST['DISPLAY_END_DATE'],0,10)." 23:59:59";
	$DISPLAY_YN=$_POST['DISPLAY_YN'];
	
$que="update product set GLOBAL_PINFO='$GLOBAL_PINFO',
PRODUCT_TYPE='$PRODUCT_TYPE',
STYLE='$STYLE',
PRODUCT_NAME='$PRODUCT_NAME',
PRODUCT_NAME__EN='$PRODUCT_NAME__EN',
PRODUCT_NAME_CH='$PRODUCT_NAME_CH',
BRAND='$BRAND',
BRAND_NAME='$BRAND_NAME',
C_IX='$C_IX',
COMPANY='$COMPANY',
PAPER_PNAME='$PAPER_PNAME',
BUYING_COMPANY='$BUYING_COMPANY',
SHORTINFO='$SHORTINFO',
SHORTINFO_EN='$SHORTINFO_EN',
SHORTINFO_CH='$SHORTINFO_CH',
BUYINGSERVICE_COPRICE='$BUYINGSERVICE_COPRICE',
WHOLESALE_PRICE='$WHOLESALE_PRICE',
WHOLESALE_SELLPRICE='$WHOLESALE_SELLPRICE',
PROMOTION_YN='$PROMOTION_YN',
PROMOTION_CONTENTS='$PROMOTION_CONTENTS',
PROMOTION_COLOR='$PROMOTION_COLOR',
LISTPRICE='$LISTPRICE',
SELLPRICE='$SELLPRICE',
PREMIUMPRICE='$PREMIUMPRICE',
COPRICE='$COPRICE',
WHOLESALE_YN='$WHOLESALE_YN',
OFFLINE_YN='$OFFLINE_YN',
WHOLESALE_RESERVE_YN='$WHOLESALE_RESERVE_YN',
WHOLESALE_RESERVE='$WHOLESALE_RESERVE',
WHOLESALE_RESERVE_RATE='$WHOLESALE_RESERVE_RATE',
WHOLESALE_RATE_TYPE='$WHOLESALE_RATE_TYPE',
RESERVE_YN='$RESERVE_YN',
RESERVE='$RESERVE',
RESERVE_RATE='$RESERVE_RATE',
RATE_TYPE='$RATE_TYPE',
SNS_BTN_YN='$SNS_BTN_YN',
SNS_BTN='$SNS_BTN',
DELIVERY_COUPON_YN='$DELIVERY_COUPON_YN',
COUPON_USE_YN='$COUPON_USE_YN',
BIMG='$BIMG',
MIMG='$MIMG',
MSIMG='$MSIMG',
SIMG='$SIMG',
CIMG='$CIMG',
BASICINFO='$BASICINFO',
BASICINFO_EN='$BASICINFO_EN',
BASICINFO_CH='$BASICINFO_CH',
M_BASICINFO='$M_BASICINFO',
ICONS='$ICONS',
STATE='$STATE',
PRODUCT_WEIGHT='$PRODUCT_WEIGHT',
IS_ADULT='$IS_ADULT',
IS_MOBILE_USE='$IS_MOBILE_USE',
DISP='$DISP',
MOVIE='$MOVIE',
VIEWORDER='$VIEWORDER',
TRADE_ADMIN='$TRADE_ADMIN',
MD_CODE='$MD_CODE',
SELL_ING_CNT='$SELL_ING_CNT',
STOCK='$STOCK',
SAFESTOCK='$SAFESTOCK',
AVAILABLE_STOCK='$AVAILABLE_STOCK',
REMAIN_STOCK='$REMAIN_STOCK',
VIEW_CNT='$VIEW_CNT',
ORDER_CNT='$ORDER_CNT',
RECOMMEND_CNT='$RECOMMEND_CNT',
WISH_CNT='$WISH_CNT',
AFTER_SCORE='$AFTER_SCORE',
AFTER_CNT='$AFTER_CNT',
PRODUCT_POINT='$PRODUCT_POINT',
PRODUCT_LEVEL='$PRODUCT_LEVEL',
SEARCH_KEYWORD='$SEARCH_KEYWORD',
REG_CATEGORY='$REG_CATEGORY',
OPTION_STOCK_YN='$OPTION_STOCK_YN',
SUPPLY_COMPANY='$SUPPLY_COMPANY',
INVENTORY_INFO='$INVENTORY_INFO',
SURTAX_YORN='$SURTAX_YORN',
DELIVERY_COMPANY='$DELIVERY_COMPANY',
ONE_COMMISSION='$ONE_COMMISSION',
COMMISSION='$COMMISSION',
WHOLESALE_COMMISSION='$WHOLESALE_COMMISSION',
ACCOUNT_TYPE='$ACCOUNT_TYPE',
CUPON_USE_YN='$CUPON_USE_YN',
STOCK_USE_YN='$STOCK_USE_YN',
DELIVERY_POLICY='$DELIVERY_POLICY',
DELIVERY_PRODUCT_POLICY='$DELIVERY_PRODUCT_POLICY',
DELIVERY_PACKAGE='$DELIVERY_PACKAGE',
DELIVERY_FREEPRICE='$DELIVERY_FREEPRICE',
DELIVERY_PRICE='$DELIVERY_PRICE',
DELIVERY_TYPE='$DELIVERY_TYPE',
FREE_DELIVERY_YN='$FREE_DELIVERY_YN',
FREE_DELIVERY_COUNT='$FREE_DELIVERY_COUNT',
IS_SELL_DATE='$IS_SELL_DATE',
SELL_PRIOD_SDATE='$SELL_PRIOD_SDATE',
SELL_PRIOD_EDATE='$SELL_PRIOD_EDATE',
ALLOW_MAX_CNT='$ALLOW_MAX_CNT',
WHOLESALE_ALLOW_MAX_CNT='$WHOLESALE_ALLOW_MAX_CNT',
ALLOW_BASIC_CNT='$ALLOW_BASIC_CNT',
WHOLESALE_ALLOW_BASIC_CNT='$WHOLESALE_ALLOW_BASIC_CNT',
ALLOW_ORDER_TYPE='$ALLOW_ORDER_TYPE',
ALLOW_ORDER_CNT_BYONESELL='$ALLOW_ORDER_CNT_BYONESELL',
ALLOW_ORDER_CNT_BYONEPERSON='$ALLOW_ORDER_CNT_BYONEPERSON',
ALLOW_ORDER_MINIMUM_CNT='$ALLOW_ORDER_MINIMUM_CNT',
ALLOW_BYONEPERSON_CNT='$ALLOW_BYONEPERSON_CNT',
WHOLESALE_ALLOW_BYONEPERSON_CNt='$WHOLESALE_ALLOW_BYONEPERSON_CNt',
MD_ONE_COMMISSION='$MD_ONE_COMMISSION',
MD_DISCOUNT_NAME='$MD_DISCOUNT_NAME',
MD_SELL_DATE_USE='$MD_SELL_DATE_USE',
MD_SELL_PRIOD_SDATE='$MD_SELL_PRIOD_SDATE',
MD_SELL_PRIOD_EDATE='$MD_SELL_PRIOD_EDATE',
WHOLE_HEAD_COMPANY_SALE_RATE='$WHOLE_HEAD_COMPANY_SALE_RATE',
WHOLE_SELLER_COMPANY_SALE_RATE='$WHOLE_SELLER_COMPANY_SALE_RATE',
HEAD_COMPANY_SALE_RATE='$HEAD_COMPANY_SALE_RATE',
SELLER_COMPANY_SALE_RATE='$SELLER_COMPANY_SALE_RATE',
ORIGIN='$ORIGIN',
MAKE_DATE='$MAKE_DATE',
EXPIRY_DATE='$EXPIRY_DATE',
MANDATORY_TYPE='$MANDATORY_TYPE',
RELATION_PRODUCT_CNT='$RELATION_PRODUCT_CNT',
RELATION_DISPLAY_ORDER_TYPE='$RELATION_DISPLAY_ORDER_TYPE',
RELATION_DISPLAY_ORDER_DATE='$RELATION_DISPLAY_ORDER_DATE',
RELATION_DISPLAY_TYPE='$RELATION_DISPLAY_TYPE',
BARCODE='$BARCODE',
INPUT_DATE='$INPUT_DATE',
IS_AUTO_CHANGE='$IS_AUTO_CHANGE',
AUTO_CHANGE_STATE='$AUTO_CHANGE_STATE',
SUBSTITUDE_YN='$SUBSTITUDE_YN',
SUBSTITUDE_TOTAL='$SUBSTITUDE_TOTAL',
SUBSTITUDE_SELLER='$SUBSTITUDE_SELLER',
SUBSTITUDE_RATE='$SUBSTITUDE_RATE',
ETC1='$ETC1',
ETC2='$ETC2',
ETC3='$ETC3',
ETC4='$ETC4',
ETC5='$ETC5',
ETC6='$ETC6',
ETC7='$ETC7',
ETC8='$ETC8',
ETC9='$ETC9',
ETC10='$ETC10',
DOWNLOAD_IMG='$DOWNLOAD_IMG',
DOWNLOAD_DESC='$DOWNLOAD_DESC',
HOTCON_EVENT_ID='$HOTCON_EVENT_ID',
HOTCON_PCODE='$HOTCON_PCODE',
CO_GOODS='$CO_GOODS',
CO_PID='$CO_PID',
CO_COMPANY_ID='$CO_COMPANY_ID',
BS_GOODS_URL='$BS_GOODS_URL',
BS_SITE='$BS_SITE',
PRICE_POLICY='$PRICE_POLICY',
CURRENCY_IX='$CURRENCY_IX',
ROUND_PRECISION='$ROUND_PRECISION',
ROUND_TYPE='$ROUND_TYPE',
EDITDATE='$EDITDATE',
NAVER_UPDATE_DATE='$NAVER_UPDATE_DATE',
DISP_NAVER='$DISP_NAVER',
DISP_DAUM='$DISP_DAUM',
ADD_INDEX_DATE='$ADD_INDEX_DATE',
ADD_INDEX_DATE2='$ADD_INDEX_DATE2',
IS_POS_LINK='$IS_POS_LINK',
IS_ERP_LINK='$IS_ERP_LINK',
ADD_STATUS='$ADD_STATUS',
CATEGORY_ADD_INFOS='$CATEGORY_ADD_INFOS',
REGDATE_DESC='$REGDATE_DESC',
REG_CHARGER_IX='$REG_CHARGER_IX',
REG_CHARGER_NAME='$REG_CHARGER_NAME',
GIFT_SPRICE='$GIFT_SPRICE',
GIFT_EPRICE='$GIFT_EPRICE',
PRICE_DISP_YN='$PRICE_DISP_YN',
REG_STANDARD_CATEGORY='$REG_STANDARD_CATEGORY',
DISPLAY_YN='$DISPLAY_YN',
DISPLAY_START_DATE='$DISPLAY_START_DATE',
DISPLAY_END_DATE='$DISPLAY_END_DATE' 
where PRODUCT_ID='".$PRODUCT_ID."'";

//echo $que;

$sql=$mysqli->query($que) or die("4:".$mysqli->error);

if($sql){

	
	$mysqli->query("delete from category_relation where PRODUCT_ID='".$PRODUCT_ID."'") or die("1:".$mysqli->error);
	$mysqli->query("delete from product_material_info where PRODUCT_ID='".$PRODUCT_ID."'") or die("1:".$mysqli->error);
	$mysqli->query("delete from product_color where PRODUCT_ID='".$PRODUCT_ID."'") or die("1:".$mysqli->error);

	for($j=0;$j<sizeof($cate1);$j++){

		if($cate2[$j]){
			$ca=$cate2[$j];
		}else{
			$ca=$cate1[$j];
		}

		$que="insert into category_relation values ('','$ca',
		'$PRODUCT_ID',
		'1',
		'$BASIC',
		'$INSERT_YN',
		now())";
//		echo $que."<br>";
		$mysqli->query($que) or die("1:".$mysqli->error);
	}

	for($j=0;$j<sizeof($mate);$j++){

		$que="insert into product_material_info values ('','$PRODUCT_ID','$mate[$j]','$pt[$j]',now(),now())";
//		echo $que."<br>";
		$mysqli->query($que) or die("2:".$mysqli->error);
	}

	for($j=0;$j<sizeof($COLOR);$j++){

		$que="insert into product_color values ('','$PRODUCT_ID','$COLOR[$j]','$COLOR_EN','$COLOR_CH[$j]',now(),now())";
//		echo $que."<br>";
		$mysqli->query($que) or die("3:".$mysqli->error);
	}


	location_is_close('수정했습니다.');
}

?>